apiVersion: v1
kind: Service
metadata:
  name: chaty-service
  namespace: default
  labels:
    app: chaty
spec:
  type: NodePort
  ports:
  - name: chaty-port
    nodePort: 30501
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: chaty